// unavailable ingredients are commented out
export const availableIngredients = [
  "vodka",
  "tequila",
  "whiskey",
  // "rum",
  "white rum",
  "gin",
  //"lemon vodka",
  "triple sec",
  "blue curacao",
  "lime juice",
  "cranberry juice",
  "orange juice",
  //"apple juice",
  "tomato juice",
  "lemon juice",
  //"orange liqueur",
  //"melon liqueur",
  //"banana liqueur",
  // "almond liqueur",
  // "coffee liqueur",
  // "dry vermouth",
  "peach schnapps",
  "irish cream",
  "creme de cacao",
  "cola",
  // "grapefruit soda",
  "tonic",
  "ice",
  "salt",
  "sugar",
  "black pepper",
  "tajin powder",
  "simple syrup",
  "grenadine syrup",
  // "whipped cream",
  "fresh cream",
  // "ice cream",
  //"almond syrup",
  "sweet and sour",
  "water",
  "soda water",
  "ginger beer",
  // "mint leaves",
  // "Hpnotiq",
  "Jagermeister",
  //"Oreos",
  // "olives",
  "jalapenos",
];

//

//

//

//

//

//

export const drinks = [
  // cocktails
  {
    name: "Moscow Mule",
    type: "cocktails",
    ingredients: ["vodka", "lime juice", "ginger beer", "ice"],
    origin: [""],
    image: "image-moscow-mule.jpg",
  },
  {
    name: "Margarita",
    type: "cocktails",
    ingredients: [
      "tequila",
      "triple sec",
      "lime juice",
      "simple syrup",
      "salt",
      "ice",
    ],
    origin: ["Mexico"],
    image: "image-margarita.jpg",
  },
  {
    name: "Blue Margarita",
    type: "cocktails",
    ingredients: [
      "tequila",
      "blue curacao",
      "lime juice",
      "simple syrup",
      "salt",
      "ice",
    ],
    origin: [""],
    image: "image-blue-margarita.jpg",
  },
  {
    name: "Blue Cosmo",
    type: "cocktails",
    ingredients: ["vodka", "blue curacao", "cranberry juice", "ice"],
    origin: [""],
    image: "image-blue-cosmo.jpg",
  },
  {
    name: "White Russian",
    type: "cocktails",
    ingredients: ["vodka", "coffee liqueur", "fresh cream", "ice"],
    origin: [""],
    image: "image-white-russian.jpg",
  },
  {
    name: "Pina Colada",
    type: "cocktails",
    ingredients: ["white rum", "coconut cream", "pineapple juice", "ice"],
    origin: [""],
    image: "image-pina-colada.jpg",
  },
  {
    name: "Cuba Libre",
    type: "cocktails",
    ingredients: ["rum", "cola", "lime juice", "ice"],
    origin: [""],
    image: "image-cuba-libre.jpg",
  },

  {
    name: "Sailors Sunrise",
    type: "cocktails",
    ingredients: ["rum", "orange juice", "grenadine syrup", "ice"],
    origin: [""],
    image: "image-sailors-sunrise.jpg",
  },
  {
    name: "Bay Breeze",
    type: "cocktails",
    ingredients: ["vodka", "cranberry juice", "pineapple juice", "ice"],
    origin: [""],
    image: "image-bay-breeze.jpg",
  },
  {
    name: "Blue Arrow",
    type: "cocktails",
    ingredients: ["gin", "triple sec", "blue curacao", "lime juice", "ice"],
    origin: [""],
    image: "image-blue-arrow.jpg",
  },
  {
    name: "Gin Martini",
    type: "cocktails",
    ingredients: ["gin", "dry vermouth", "olives", "ice"],
    origin: [""],
    image: "image-gin-martini.jpg",
  },

  {
    name: "Spicy Margarita",
    type: "cocktails",
    ingredients: [
      "tequila",
      "triple sec",
      "simple syrup",
      "lime juice",
      "tajin powder",
      "jalapenos",
      "ice",
    ],
    origin: [""],
    image: "image-spicy-margarita.jpg",
  },

  {
    name: "Hurricane",
    type: "cocktails",
    ingredients: [
      "white rum",
      "rum",
      "lime juice",
      "orange juice",
      "simple syrup",
      "grenadine syrup",
      "ice",
    ],
    origin: [""],
    image: "image-hurricane.jpeg",
  },
  {
    name: "Tequila Sunrise",
    type: "cocktails",
    ingredients: ["tequila", "orange juice", "grenadine syrup", "ice"],
    origin: [""],
    image: "image-tequila-sunrise.jpeg",
  },
  {
    name: "Sex On The Beach",
    type: "cocktails",
    ingredients: [
      "vodka",
      "peach schnapps",
      "orange juice",
      "cranberry juice",
      "ice",
    ],
    origin: [""],
    image: "image-sex-beach.jpg",
  },
  {
    name: "Paloma",
    type: "cocktails",
    ingredients: ["tequila", "lime juice", "grapefruit soda", "ice"],
    origin: [""],
    image: "image-paloma.jpg",
  },
  {
    name: "Mojito",
    type: "cocktails",
    ingredients: [
      "white rum",
      "soda water",
      "simple syrup",
      "mint leaves",
      "ice",
    ],
    origin: ["Cuba"],
    image: "image-mojito.jpg",
  },
  {
    name: "Mai Tai",
    type: "cocktails",
    ingredients: [
      "rum",
      "white rum",
      "orange liqueur",
      "lime juice",
      "almond syrup",
      "orange juice",
      "ice",
    ],
    origin: ["USA"],
    image: "image-mai-tai.jpg",
  },
  {
    name: "Daiquiri",
    type: "cocktails",
    ingredients: ["white rum", "lime juice", "sugar"],
    origin: ["USA", "Cuba"],
    image: "image-daiquiri.jpg",
  },
  {
    name: "Cosmopolitan",
    type: "cocktails",
    ingredients: [
      "lemon vodka",
      "triple sec",
      "cranberry juice",
      "lime juice",
      "ice",
    ],
    origin: ["USA"],
    image: "image-cosmopolitan.jpg",
  },
  {
    name: "Bloody Marry",
    type: "cocktails",
    ingredients: [
      "vodka",
      "tomato juice",
      "lemon juice",
      "salt",
      "black pepper",
      "ice",
    ],
    origin: ["USA", "France"],
    image: "image-bloody-mary.jpg",
  },
  {
    name: "Long Island",
    type: "cocktails",
    ingredients: [
      "vodka",
      "white rum",
      "gin",
      "tequila",
      "triple sec",
      "sweeet and sour",
      "cola",
      "ice",
    ],
    origin: [""],
    image: "image-long-island.jpeg",
  },
  {
    name: "Whiskey Sour",
    type: "cocktails",
    ingredients: ["whiskey", "lemon juice", "simple syrup", "ice"],
    origin: [""],
    image: "image-whiskey-sour.jpg",
  },
  {
    name: "Green Parrot",
    type: "cocktails",
    ingredients: [
      "vodka",
      "white rum",
      "dry vermouth",
      "blue curacao",
      "creme de cacao",
      "orange juice",
      "ice",
    ],
    origin: [""],
    image: "image-green-parrot.jpg",
  },

  // shots
  {
    name: "Kamikaze",
    type: "shots",
    ingredients: ["vodka", "triple sec", "lime juice"],
    origin: ["USA", "Japan"],
    image: "image-kamikaze.jpg",
  },
  {
    name: "Blowjob",
    type: "shots",
    ingredients: [
      "almond liqueur",
      "coffee liqueur",
      "irish cream",
      "whipped cream",
    ],
    origin: [""],
    image: "image-blowjob.png",
  },
  {
    name: "Deep Ocean",
    type: "shots",
    ingredients: ["blue curacao", "white rum", "Hpnotiq"],
    origin: [""],
    image: "image-deep-ocean.jpg",
  },
  {
    name: "Lemon Drop",
    type: "shots",
    ingredients: ["vodka", "lemon juice", "simple syrup", "salt", "ice"],
    origin: [""],
    image: "image-lemon-drop.jpg",
  },
  {
    name: "Alien Brain Hemorage Shooter",
    type: "shots",
    ingredients: [
      "peach schnapps",
      "irish cream",
      "blue curacao",
      "grenadine syrup",
    ],
    origin: [""],
    image: "image-alien-brain-hemorage.jpg",
  },
  {
    name: "Monkey Brain Shot",
    type: "shots",
    ingredients: ["vodka", "lemon juice", "irish cream", "grenadine syrup"],
    origin: [""],
    image: "image-monkey-brain.jpg",
  },
  // long drinks
  {
    name: "Whiskey Cola",
    type: "long drinks",
    ingredients: ["whiskey", "cola", "ice"],
    origin: ["USA"],
    image: "image-whiskey-cola.jpg",
  },
  {
    name: "Gin Tonic",
    type: "long drinks",
    ingredients: ["gin", "tonic", "ice"],
    origin: ["UK", "India"],
    image: "image-gin-tonic.jpg",
  },
  {
    name: "Vodka Orange",
    type: "long drinks",
    ingredients: ["vodka", "orange juice", "ice"],
    origin: [""],
    image: "image-vodka-orange.jpg",
  },
  {
    name: "Vodka Cranberry",
    type: "long drinks",
    ingredients: ["vodka", "cranberry juice", "ice"],
    origin: ["UK", "India"],
    image: "image-vodka-cranberry.jpeg",
  },
  {
    name: "Rum and Coke",
    type: "long drinks",
    ingredients: ["rum", "cola", "ice"],
    origin: [""],
    image: "image-rum-coke.jpg",
  },
  // other
  {
    name: "Coffee",
    type: "other",
    ingredients: [],
    origin: [""],
    image: "image-coffee.jpg",
  },
  {
    name: "Black Russian",
    type: "other",
    ingredients: ["vodka", "coffee liqueur", "ice"],
    origin: [""],
    image: "image-black-russian.jpg",
  },
  {
    name: "Jagermeister Oreo Milkshake",
    type: "other",
    ingredients: ["Jagermeister", "Oreos", "ice cream"],
    origin: [],
    image: "image-Jager-Oreo-shake.jpg",
  },
];
