// unavailable ingredients are commented out
export const availableIngredients = [
  "vodka",
  "tequila",
  "whiskey",
  // "rum",
  "white rum",
  "gin",
  //"lemon vodka",
  "triple sec",
  "blue curacao",
  "lime juice",
  "cranberry juice",
  "orange juice",
  //"apple juice",
  "tomato juice",
  "lemon juice",
  //"orange liqueur",
  //"melon liqueur",
  //"banana liqueur",
  // "almond liqueur",
  // "coffee liqueur",
  // "dry vermouth",
  "peach schnapps",
  "irish cream",
  "creme de cacao",
  "cola",
  // "grapefruit soda",
  "tonic",
  "ice",
  "salt",
  "sugar",
  "black pepper",
  "tajin powder",
  "simple syrup",
  "grenadine syrup",
  "coconut syrup",
  "honey syrup",
  // "whipped cream",
  "fresh cream",
  // "ice cream",
  //"almond syrup",
  // "sweet and sour",
  "water",
  "soda water",
  "ginger beer",
  "coffee",
  // "mint leaves",
  // "Hpnotiq",
  "Jagermeister",
  //"Oreos",
  // "olives",
  "jalapenos",
  "tabasco sauce",
];

//

//

//

//

export const allIngredients = [
  { id: 27, name: "vodka" },
  { id: 28, name: "tequila" },
  { id: 30, name: "whiskey" },
  { id: 40, name: "rum" },
  { id: 50, name: "white rum" },
  { id: 60, name: "gin" },
  { id: 70, name: "lemon vodka" },
  { id: 80, name: "triple sec" },
  { id: 90, name: "blue curacao" },
  { id: 100, name: "lime juice" },
  { id: 110, name: "cranberry juice" },
  { id: 120, name: "orange juice" },
  { id: 130, name: "apple juice" },
  { id: 140, name: "tomato juice" },
  { id: 150, name: "lemon juice" },
  { id: 160, name: "orange liqueur" },
  { id: 170, name: "melon liqueur" },
  { id: 180, name: "banana liqueur" },
  { id: 190, name: "almond liqueur" },
  { id: 200, name: "coffee liqueur" },
  { id: 210, name: "dry vermouth" },
  { id: 220, name: "peach schnapps" },
  { id: 230, name: "irish cream" },
  { id: 240, name: "creme de cacao" },
  { id: 250, name: "cola" },
  { id: 260, name: "grapefruit soda" },
  { id: 270, name: "tonic" },
  { id: 280, name: "ice" },
  { id: 290, name: "salt" },
  { id: 300, name: "sugar" },
  { id: 310, name: "black pepper" },
  { id: 320, name: "tajin powder" },
  { id: 330, name: "simple syrup" },
  { id: 340, name: "grenadine syrup" },
  { id: 350, name: "coconut syrup" },
  { id: 360, name: "whipped cream" },
  { id: 370, name: "fresh cream" },
  { id: 380, name: "ice cream" },
  { id: 390, name: "almond syrup" },
  { id: 400, name: "sweet and sour" },
  { id: 410, name: "water" },
  { id: 420, name: "soda water" },
  { id: 430, name: "ginger beer" },
  { id: 440, name: "mint leaves" },
  { id: 450, name: "Hpnotiq" },
  { id: 460, name: "Jagermeister" },
  { id: 470, name: "Oreos" },
  { id: 480, name: "olives" },
  { id: 490, name: "jalapenos" },
  { id: 500, name: "tabasco sauce" },
];
//

//

export const drinks = [
  // cocktails
  {
    name: "Moscow Mule",
    type: "cocktails",
    ingredients: ["vodka", "lime juice", "ginger beer", "ice"],
    origin: [""],
    image: "image-moscow-mule.jpg",
  },
  {
    name: "Ginger Mule",
    type: "cocktails",
    ingredients: ["gin", "lime juice", "ginger beer", "ice"],
    origin: [""],
    image: "image.jpg",
  },
  {
    name: "Margarita",
    type: "cocktails",
    ingredients: [
      "tequila",
      "triple sec",
      "lime juice",
      "simple syrup",
      "salt",
      "ice",
    ],
    origin: ["Mexico"],
    image: "image-margarita.jpg",
  },
  {
    name: "Blue Margarita",
    type: "cocktails",
    ingredients: [
      "tequila",
      "blue curacao",
      "lime juice",
      "simple syrup",
      "salt",
      "ice",
    ],
    origin: [""],
    image: "image-blue-margarita.jpg",
  },
  {
    name: "Blue Cosmo",
    type: "cocktails",
    ingredients: ["vodka", "blue curacao", "cranberry juice", "ice"],
    origin: [""],
    image: "image-blue-cosmo.jpg",
  },
  {
    name: "White Russian",
    type: "cocktails",
    ingredients: ["vodka", "coffee liqueur", "fresh cream", "ice"],
    origin: [""],
    image: "image-white-russian.jpg",
  },
  {
    name: "Pina Colada",
    type: "cocktails",
    ingredients: ["white rum", "coconut syrup", "pineapple juice", "ice"],
    origin: [""],
    image: "image-pina-colada.jpg",
  },
  {
    name: "Cuba Libre",
    type: "cocktails",
    ingredients: ["rum", "cola", "lime juice", "ice"],
    origin: [""],
    image: "image-cuba-libre.jpg",
  },

  {
    name: "Sailors Sunrise",
    type: "cocktails",
    ingredients: ["rum", "orange juice", "grenadine syrup", "ice"],
    origin: [""],
    image: "image-sailors-sunrise.jpg",
  },
  {
    name: "Bay Breeze",
    type: "cocktails",
    ingredients: ["vodka", "cranberry juice", "pineapple juice", "ice"],
    origin: [""],
    image: "image-bay-breeze.jpg",
  },
  {
    name: "Blue Arrow",
    type: "cocktails",
    ingredients: ["gin", "triple sec", "blue curacao", "lime juice", "ice"],
    origin: [""],
    image: "image-blue-arrow.jpg",
  },
  {
    name: "Gin Martini",
    type: "cocktails",
    ingredients: ["gin", "dry vermouth", "olives", "ice"],
    origin: [""],
    image: "image-gin-martini.jpg",
  },

  {
    name: "Spicy Margarita",
    type: "cocktails",
    ingredients: [
      "tequila",
      "triple sec",
      "simple syrup",
      "lime juice",
      "tajin powder",
      "jalapenos",
      "ice",
    ],
    origin: [""],
    image: "image-spicy-margarita.jpg",
  },

  {
    name: "Hurricane",
    type: "cocktails",
    ingredients: [
      "white rum",
      "rum",
      "lime juice",
      "orange juice",
      "simple syrup",
      "grenadine syrup",
      "ice",
    ],
    origin: [""],
    image: "image-hurricane.jpeg",
  },
  {
    name: "Tequila Sunrise",
    type: "cocktails",
    ingredients: ["tequila", "orange juice", "grenadine syrup", "ice"],
    origin: [""],
    image: "image-tequila-sunrise.jpeg",
  },
  {
    name: "Blood Orange Margarita",
    type: "cocktails",
    ingredients: [
      "tequila",
      "blood orange juice",
      "triple sec",
      "lime juice",
      "simple syrup",
      "salt",
      "ice",
    ],
    origin: [""],
    image: "image-blood-orange-margarita.jpg",
  },
  {
    name: "Sex On The Beach",
    type: "cocktails",
    ingredients: [
      "vodka",
      "peach schnapps",
      "orange juice",
      "cranberry juice",
      "ice",
    ],
    origin: [""],
    image: "image-sex-beach.jpg",
  },
  {
    name: "Paloma",
    type: "cocktails",
    ingredients: ["tequila", "lime juice", "grapefruit soda", "ice"],
    origin: [""],
    image: "image-paloma.jpg",
  },
  {
    name: "Mojito",
    type: "cocktails",
    ingredients: [
      "white rum",
      "soda water",
      "simple syrup",
      "mint leaves",
      "ice",
    ],
    origin: ["Cuba"],
    image: "image-mojito.jpg",
  },
  {
    name: "Mai Tai",
    type: "cocktails",
    ingredients: [
      "rum",
      "white rum",
      "orange liqueur",
      "lime juice",
      "almond syrup",
      "orange juice",
      "ice",
    ],
    origin: ["USA"],
    image: "image-mai-tai.jpg",
  },
  {
    name: "Daiquiri",
    type: "cocktails",
    ingredients: ["white rum", "lime juice", "simple syrup", "ice"],
    origin: ["USA", "Cuba"],
    image: "image-daiquiri.jpg",
  },
  {
    name: "Honeysuckle Daiquiri",
    type: "cocktails",
    ingredients: [
      "white rum",
      "lemon juice",
      "orange juice",
      "honey syrup",
      "ice",
    ],
    origin: ["USA", "Cuba"],
    image: "image-honey-daiquiri.jpg",
  },
  {
    name: "Cosmopolitan",
    type: "cocktails",
    ingredients: [
      "vodka",
      "triple sec",
      "cranberry juice",
      "lime juice",
      "ice",
    ],
    origin: ["USA"],
    image: "image-cosmopolitan.jpg",
  },
  {
    name: "Black Russian",
    type: "cocktails",
    ingredients: ["vodka", "coffee liqueur", "ice"],
    origin: [""],
    image: "image-black-russian.jpg",
  },
  {
    name: "Irish Coffee",
    type: "cocktails",
    ingredients: ["whiskey", "coffee", "sugar", "whipped cream"],
    origin: [""],
    image: "image-irish-coffee.jpg",
  },
  {
    name: "Espresso Martini",
    type: "cocktails",
    ingredients: ["vodka", "coffee", "coffee liqueur", "sugar", "ice"],
    origin: [""],
    image: "image-espresso-martini.jpg",
  },
  {
    name: "Bloody Marry",
    type: "cocktails",
    ingredients: [
      "vodka",
      "tomato juice",
      "lemon juice",
      "salt",
      "black pepper",
      "tabasco sauce",
      "ice",
    ],
    origin: ["USA", "France"],
    image: "image-bloody-mary.jpg",
  },
  {
    name: "Long Island",
    type: "cocktails",
    ingredients: [
      "vodka",
      "white rum",
      "gin",
      "tequila",
      "triple sec",
      "lime juice",
      "simple syrup",
      "cola",
      "ice",
    ],
    origin: [""],
    image: "image-long-island.jpeg",
  },
  {
    name: "Whiskey Sour",
    type: "cocktails",
    ingredients: ["whiskey", "lemon juice", "simple syrup", "ice"],
    origin: [""],
    image: "image-whiskey-sour.jpg",
  },
  {
    name: "Green Parrot",
    type: "cocktails",
    ingredients: [
      "vodka",
      "white rum",
      "dry vermouth",
      "blue curacao",
      "creme de cacao",
      "orange juice",
      "ice",
    ],
    origin: [""],
    image: "image-green-parrot.jpg",
  },

  // shots
  {
    name: "Kamikaze",
    type: "shots",
    ingredients: ["vodka", "triple sec", "lime juice"],
    origin: ["USA", "Japan"],
    image: "image-kamikaze.jpg",
  },
  {
    name: "Blowjob",
    type: "shots",
    ingredients: [
      "almond liqueur",
      "coffee liqueur",
      "irish cream",
      "whipped cream",
    ],
    origin: [""],
    image: "image-blowjob.png",
  },
  {
    name: "Purple Starfucker",
    type: "shots",
    ingredients: [
      "blue curacao",
      "peach schnapps",
      "almond liqueur",
      "cranberry juice",
    ],
    origin: [""],
    image: "image.jpg",
  },
  {
    name: "Red Headed Slut",
    type: "shots",
    ingredients: ["peach schnapps", "Jagermeister", "cranberry juice"],
    origin: [""],
    image: "image.jpg",
  },
  {
    name: "Apocalypse Now",
    type: "shots",
    ingredients: ["tequila", "dry vermouth", "irish cream"],
    origin: [""],
    image: "image-apocalypse-now.png",
  },
  {
    name: "Deep Ocean",
    type: "shots",
    ingredients: ["blue curacao", "white rum", "Hpnotiq"],
    origin: [""],
    image: "image-deep-ocean.jpg",
  },
  {
    name: "Water Moccasin",
    type: "shots",
    ingredients: [
      "whiskey",
      "peach schnapps",
      "triple sec",
      "lime juice",
      "simple syrup",
    ],
    origin: [""],
    image: "image.jpg",
  },
  {
    name: "Lemon Drop",
    type: "shots",
    ingredients: ["vodka", "lemon juice", "simple syrup", "salt"],
    origin: [""],
    image: "image-lemon-drop.jpg",
  },
  {
    name: "Alien Brain Hemorage",
    type: "shots",
    ingredients: [
      "peach schnapps",
      "irish cream",
      "blue curacao",
      "grenadine syrup",
    ],
    origin: [""],
    image: "image-alien-brain-hemorage.jpg",
  },
  {
    name: "Monkey Brain",
    type: "shots",
    ingredients: ["vodka", "lemon juice", "irish cream", "grenadine syrup"],
    origin: [""],
    image: "image-monkey-brain.jpg",
  },
  // long drinks
  {
    name: "Whiskey Cola",
    type: "long drinks",
    ingredients: ["whiskey", "cola", "ice"],
    origin: ["USA"],
    image: "image-whiskey-cola.jpg",
  },
  {
    name: "Gin Tonic",
    type: "long drinks",
    ingredients: ["gin", "tonic", "ice"],
    origin: ["UK", "India"],
    image: "image-gin-tonic.jpg",
  },
  {
    name: "Vodka Orange",
    type: "long drinks",
    ingredients: ["vodka", "orange juice", "ice"],
    origin: [""],
    image: "image-vodka-orange.jpg",
  },
  {
    name: "Vodka Cranberry",
    type: "long drinks",
    ingredients: ["vodka", "cranberry juice", "ice"],
    origin: ["UK", "India"],
    image: "image-vodka-cranberry.jpeg",
  },
  {
    name: "Rum Cola",
    type: "long drinks",
    ingredients: ["rum", "cola", "ice"],
    origin: [""],
    image: "image-rum-coke.jpg",
  },
  // other
  {
    name: "Coffee",
    type: "other",
    ingredients: ["coffee"],
    origin: [""],
    image: "image-coffee.jpg",
  },

  {
    name: "Jagermeister Oreo Milkshake",
    type: "other",
    ingredients: ["Jagermeister", "Oreos", "ice cream"],
    origin: [],
    image: "image-Jager-Oreo-shake.jpg",
  },
];
